# Generated by Django 5.2.6 on 2025-09-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('site_icon', models.URLField()),
                ('link', models.URLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
