# Generated by Django 5.2.6 on 2025-09-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'ordering': ['-fecha'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.AlterField(
            model_name='noticias',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
