# Generated by Django 5.2.6 on 2025-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_api_app', '0002_alter_noticias_options_alter_noticias_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
