# Generated by Django 5.2.6 on 2025-09-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_api_app', '0003_noticias_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='site_icon',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
